# Generated by Django 5.2.11 on 2026-03-28 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_guests', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('additional_guests', models.JSONField(blank=True, default=list)),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
